// <auto-generated />
using System;
using ChronosDotnetApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChronosDotnetApi.Migrations
{
    [DbContext(typeof(ChronosDbContext))]
    [Migration("20260609124848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChronosDotnetApi.Domain.AssetBalance", b =>
                {
                    b.Property<int>("IdAsset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_asset");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsset"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("balance");

                    b.Property<int>("IdNode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_node");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("last_update");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("symbol");

                    b.HasKey("IdAsset");

                    b.HasIndex("IdNode");

                    b.ToTable("T_CDTN_ASSET_BALANCES");
                });

            modelBuilder.Entity("ChronosDotnetApi.Domain.Node", b =>
                {
                    b.Property<int>("IdNode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_node");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNode"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("name");

                    b.Property<string>("NetworkAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("network_address");

                    b.HasKey("IdNode");

                    b.ToTable("T_CDTN_NODE_REGISTRY");
                });

            modelBuilder.Entity("ChronosDotnetApi.Domain.NodeLink", b =>
                {
                    b.Property<int>("IdRoute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_route");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoute"));

                    b.Property<decimal>("BandwidthKbps")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("bandwidth_kbps");

                    b.Property<int>("SourceNodeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("source_node");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.Property<int>("TargetNodeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("target_node");

                    b.HasKey("IdRoute");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("T_CDTN_DYNAMIC_ROUTES");
                });

            modelBuilder.Entity("ChronosDotnetApi.Domain.AssetBalance", b =>
                {
                    b.HasOne("ChronosDotnetApi.Domain.Node", "Node")
                        .WithMany("Balances")
                        .HasForeignKey("IdNode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ChronosDotnetApi.Domain.NodeLink", b =>
                {
                    b.HasOne("ChronosDotnetApi.Domain.Node", "SourceNode")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronosDotnetApi.Domain.Node", "TargetNode")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("ChronosDotnetApi.Domain.Node", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
